import { db } from "./db";
import { products } from "@shared/schema";

const sampleProducts = [
  {
    name: "HP OfficeJet Pro 9025e All-in-One Wireless Color Printer",
    slug: "hp-officejet-pro-9025e",
    description: "The HP OfficeJet Pro 9025e delivers professional-quality color printing with fast speeds up to 24 ppm. Features automatic two-sided printing, scanning, copying, and faxing. Perfect for small offices and home businesses with high-volume printing needs.",
    price: "329.99",
    originalPrice: "399.99",
    image: "/attached_assets/generated_images/HP_OfficeJet_Pro_printer_89015997.png",
    category: "office",
    stock: 45,
    rating: null,
    reviewCount: 0,
    specifications: JSON.stringify({
      "Print Speed (Black)": "24 ppm",
      "Print Speed (Color)": "20 ppm",
      "Print Resolution": "4800 x 1200 dpi",
      "Paper Capacity": "250 sheets",
      "Connectivity": "WiFi, Ethernet, USB",
      "Duplex Printing": "Automatic",
      "Monthly Duty Cycle": "25,000 pages",
    }),
    features: [
      "Automatic two-sided printing",
      "50-sheet automatic document feeder",
      "2.7-inch color touchscreen",
      "Mobile printing support (AirPrint, Mopria)",
      "Fast first page out",
      "HP Smart App compatible",
      "Voice-activated printing",
      "Self-healing WiFi",
    ],
    inStock: true,
  },
  {
    name: "HP DeskJet 4155e All-in-One Wireless Color Printer",
    slug: "hp-deskjet-4155e",
    description: "Affordable and reliable, the HP DeskJet 4155e is perfect for home use. Print, scan, and copy with ease using wireless connectivity. Compact design fits anywhere, and HP+ delivers ongoing value with smart features and instant ink enrollment.",
    price: "129.99",
    originalPrice: null,
    image: "/attached_assets/generated_images/HP_DeskJet_home_printer_88c9a819.png",
    category: "home",
    stock: 78,
    rating: null,
    reviewCount: 0,
    specifications: JSON.stringify({
      "Print Speed (Black)": "8.5 ppm",
      "Print Speed (Color)": "5.5 ppm",
      "Print Resolution": "4800 x 1200 dpi",
      "Paper Capacity": "60 sheets",
      "Connectivity": "WiFi, USB",
      "Duplex Printing": "Manual",
      "Monthly Duty Cycle": "1,000 pages",
    }),
    features: [
      "Wireless printing from smartphone or tablet",
      "HP Smart App for easy setup",
      "Borderless photo printing",
      "Compact space-saving design",
      "Energy Star certified",
      "Instant Ink eligible",
      "Easy mobile setup",
    ],
    inStock: true,
  },
  {
    name: "HP OfficeJet 250 Mobile All-in-One Portable Printer",
    slug: "hp-officejet-250-mobile",
    description: "Print, scan, and copy from anywhere with the ultra-portable HP OfficeJet 250. Battery-powered for true mobility, this printer delivers professional results on the go. Perfect for remote workers and traveling professionals.",
    price: "399.99",
    originalPrice: "449.99",
    image: "/attached_assets/generated_images/HP_portable_mobile_printer_cace2eb0.png",
    category: "portable",
    stock: 23,
    rating: null,
    reviewCount: 0,
    specifications: JSON.stringify({
      "Print Speed (Black)": "10 ppm",
      "Print Speed (Color)": "7 ppm",
      "Print Resolution": "4800 x 1200 dpi",
      "Paper Capacity": "50 sheets",
      "Connectivity": "WiFi, USB",
      "Battery Life": "Up to 500 pages",
      "Weight": "6.6 lbs",
    }),
    features: [
      "Built-in rechargeable battery",
      "Print up to 500 pages per charge",
      "Compact and lightweight design",
      "Wireless printing from mobile devices",
      "Auto document feeder",
      "HP Smart App compatible",
      "Quiet mode for noise-sensitive environments",
    ],
    inStock: true,
  },
  {
    name: "HP ENVY Photo 7855 All-in-One Wireless Photo Printer",
    slug: "hp-envy-photo-7855",
    description: "Create stunning photos and professional documents with the HP ENVY Photo 7855. Six-ink color system produces lab-quality photos. Features dual paper trays and borderless printing up to 8.5 x 11 inches for versatile printing options.",
    price: "249.99",
    originalPrice: "299.99",
    image: "/attached_assets/generated_images/HP_ENVY_Photo_printer_5b675a55.png",
    category: "home",
    stock: 34,
    rating: null,
    reviewCount: 0,
    specifications: JSON.stringify({
      "Print Speed (Black)": "15 ppm",
      "Print Speed (Color)": "10 ppm",
      "Print Resolution": "4800 x 1200 dpi",
      "Paper Capacity": "125 sheets (2 trays)",
      "Connectivity": "WiFi, Ethernet, USB",
      "Duplex Printing": "Automatic",
      "Photo Tray": "15 sheets",
    }),
    features: [
      "Six-ink color system for vibrant photos",
      "Borderless printing up to 8.5 x 11 inches",
      "Dual paper trays (photo and plain)",
      "2.7-inch color touchscreen",
      "Automatic two-sided printing",
      "SD card slot for direct photo printing",
      "HP Smart App with creative features",
      "Instant Ink eligible",
    ],
    inStock: true,
  },
  {
    name: "HP OfficeJet Pro 8035e All-in-One Wireless Color Printer",
    slug: "hp-officejet-pro-8035e",
    description: "Smart, efficient, and reliable - the HP OfficeJet Pro 8035e handles all your office needs. Self-healing WiFi ensures consistent connectivity, while smart tasks automate routine work. Ideal for productive small offices.",
    price: "279.99",
    originalPrice: null,
    image: "/attached_assets/generated_images/HP_OfficeJet_Pro_printer_89015997.png",
    category: "office",
    stock: 56,
    rating: null,
    reviewCount: 0,
    specifications: JSON.stringify({
      "Print Speed (Black)": "20 ppm",
      "Print Speed (Color)": "10 ppm",
      "Print Resolution": "4800 x 1200 dpi",
      "Paper Capacity": "225 sheets",
      "Connectivity": "WiFi, Ethernet, USB",
      "Duplex Printing": "Automatic",
      "Monthly Duty Cycle": "20,000 pages",
    }),
    features: [
      "Self-healing WiFi technology",
      "Smart tasks automation",
      "35-sheet automatic document feeder",
      "2.7-inch color touchscreen",
      "Voice-activated printing",
      "Mobile fax capability",
      "HP Smart App integration",
      "Advanced security features",
    ],
    inStock: true,
  },
  {
    name: "HP DeskJet 2755e Wireless All-in-One Color Printer",
    slug: "hp-deskjet-2755e",
    description: "Simple, affordable, and compact - the HP DeskJet 2755e is perfect for basic home printing needs. Easy wireless setup and smartphone printing make it ideal for students and light home use.",
    price: "89.99",
    originalPrice: null,
    image: "/attached_assets/generated_images/HP_DeskJet_home_printer_88c9a819.png",
    category: "home",
    stock: 92,
    rating: null,
    reviewCount: 0,
    specifications: JSON.stringify({
      "Print Speed (Black)": "7.5 ppm",
      "Print Speed (Color)": "5.5 ppm",
      "Print Resolution": "4800 x 1200 dpi",
      "Paper Capacity": "60 sheets",
      "Connectivity": "WiFi, USB",
      "Duplex Printing": "Manual",
      "Monthly Duty Cycle": "1,000 pages",
    }),
    features: [
      "Ultra-compact design",
      "Easy wireless setup",
      "HP Smart App for mobile printing",
      "Copy and scan functionality",
      "Energy efficient",
      "Instant Ink compatible",
      "Affordable ink cartridges",
    ],
    inStock: true,
  },
  {
    name: "HP OfficeJet Pro 9015e All-in-One Wireless Color Printer",
    slug: "hp-officejet-pro-9015e",
    description: "Professional color printing with enterprise-level features. The HP OfficeJet Pro 9015e offers fast speeds, robust security, and reliable performance for demanding office environments.",
    price: "299.99",
    originalPrice: "349.99",
    image: "/attached_assets/generated_images/HP_OfficeJet_Pro_printer_89015997.png",
    category: "office",
    stock: 41,
    rating: null,
    reviewCount: 0,
    specifications: JSON.stringify({
      "Print Speed (Black)": "22 ppm",
      "Print Speed (Color)": "18 ppm",
      "Print Resolution": "4800 x 1200 dpi",
      "Paper Capacity": "250 sheets",
      "Connectivity": "WiFi, Ethernet, USB",
      "Duplex Printing": "Automatic",
      "Monthly Duty Cycle": "25,000 pages",
    }),
    features: [
      "Fast color printing",
      "Self-healing WiFi",
      "35-sheet ADF with scan",
      "Advanced security features",
      "Smart tasks for workflow automation",
      "Voice-activated printing",
      "HP Smart App compatible",
      "Professional print quality",
    ],
    inStock: true,
  },
  {
    name: "HP ENVY Inspire 7955e All-in-One Wireless Color Printer",
    slug: "hp-envy-inspire-7955e",
    description: "Versatile all-in-one printer designed for creative home users. Print stunning photos and professional documents with ease. Features dual paper trays and intuitive touchscreen controls.",
    price: "199.99",
    originalPrice: "249.99",
    image: "/attached_assets/generated_images/HP_ENVY_Photo_printer_5b675a55.png",
    category: "home",
    stock: 67,
    rating: null,
    reviewCount: 0,
    specifications: JSON.stringify({
      "Print Speed (Black)": "15 ppm",
      "Print Speed (Color)": "10 ppm",
      "Print Resolution": "4800 x 1200 dpi",
      "Paper Capacity": "125 sheets",
      "Connectivity": "WiFi, USB",
      "Duplex Printing": "Automatic",
      "Photo Tray": "15 sheets",
    }),
    features: [
      "Dual paper trays",
      "Borderless photo printing",
      "2.7-inch color touchscreen",
      "Automatic two-sided printing",
      "HP Smart App creativity tools",
      "Self-healing WiFi",
      "Instant Ink eligible",
      "Premium build quality",
    ],
    inStock: true,
  },
];

async function seed() {
  console.log("Seeding database...");
  
  try {
    // Clear existing products
    await db.delete(products);
    console.log("Cleared existing products");

    // Insert sample products
    await db.insert(products).values(sampleProducts);
    console.log(`Inserted ${sampleProducts.length} products`);

    console.log("Database seeded successfully!");
    process.exit(0);
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
}

seed();
